[project]
name = "weather"
version = "0.1.0"
description = "Weather MCP server"
requires-python = ">=3.10,<4.0"
dependencies = [
    "mcp[cli]>=1.6.0,<2.0.0",
    "httpx>=0.28.1,<0.29.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"