version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - bank-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: bank-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  postgres-data: